export interface RawQuestion {
  id?: string;
  text: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD?: string;
  correctAnswer: "a" | "b" | "c" | "d";
  orderIndex: number;
}

export const DEFAULT_BASKETBALL_BANK = {
  title: "Kuis Bola Basket - Kelas 3 SD (Versi Dasar)",
  description:
    "Kuis pengenalan dasar bola basket untuk siswa SD: peralatan, gerakan dasar (dribbling, shooting, passing), dan sportivitas.",
  questions: [
    {
      text: "Bola basket berbentuk apa?",
      optionA: "Lonjong",
      optionB: "Bulat",
      optionC: "Kotak",
      correctAnswer: "b",
      orderIndex: 1,
    },
    {
      text: "Berapa jumlah pemain inti dalam satu tim bola basket?",
      optionA: "11 orang",
      optionB: "7 orang",
      optionC: "5 orang",
      correctAnswer: "c",
      orderIndex: 2,
    },
    {
      text: "Ke mana bola harus dimasukkan untuk mencetak poin dalam basket?",
      optionA: "Keranjang/ring",
      optionB: "Gawang",
      optionC: "Kotak",
      correctAnswer: "a",
      orderIndex: 3,
    },
    {
      text: "Apa nama gerakan memantulkan bola ke lantai sambil berjalan atau berlari?",
      optionA: "Shooting",
      optionB: "Dribbling",
      optionC: "Passing",
      correctAnswer: "b",
      orderIndex: 4,
    },
    {
      text: "Apa nama gerakan melempar/menembak bola ke arah ring?",
      optionA: "Blocking",
      optionB: "Dribbling",
      optionC: "Shooting",
      correctAnswer: "c",
      orderIndex: 5,
    },
    {
      text: "Apa nama gerakan mengoper bola ke teman satu tim?",
      optionA: "Passing",
      optionB: "Shooting",
      optionC: "Dribbling",
      correctAnswer: "a",
      orderIndex: 6,
    },
    {
      text: "Apa nama lapangan tempat bermain basket?",
      optionA: "Kolam renang",
      optionB: "Lapangan basket",
      optionC: "Lapangan sepak bola",
      correctAnswer: "b",
      orderIndex: 7,
    },
    {
      text: "Apa sebutan untuk ring tempat bola dimasukkan?",
      optionA: "Gawang",
      optionB: "Jaring ikan",
      optionC: "Ring/keranjang",
      correctAnswer: "c",
      orderIndex: 8,
    },
    {
      text: "Bagian tubuh apa yang paling sering digunakan dalam bermain basket?",
      optionA: "Tangan",
      optionB: "Kaki",
      optionC: "Kepala",
      correctAnswer: "a",
      orderIndex: 9,
    },
    {
      text: "Siapa yang memimpin jalannya pertandingan basket?",
      optionA: "Pelatih",
      optionB: "Wasit",
      optionC: "Penonton",
      correctAnswer: "b",
      orderIndex: 10,
    },
    {
      text: "Apa nama alat yang ditiup wasit untuk memberi tanda?",
      optionA: "Lonceng",
      optionB: "Terompet",
      optionC: "Peluit",
      correctAnswer: "c",
      orderIndex: 11,
    },
    {
      text: "Apa nama sepatu yang cocok dipakai saat bermain basket?",
      optionA: "Sepatu olahraga",
      optionB: "Sepatu sandal",
      optionC: "Sepatu hujan",
      correctAnswer: "a",
      orderIndex: 12,
    },
    {
      text: "Sebelum bermain basket, sebaiknya kita melakukan apa dulu?",
      optionA: "Tidur",
      optionB: "Pemanasan",
      optionC: "Makan besar",
      correctAnswer: "b",
      orderIndex: 13,
    },
    {
      text: "Apa yang harus kita lakukan jika teman kita gagal mencetak poin?",
      optionA: "Mengejeknya",
      optionB: "Mendiamkannya",
      optionC: "Menyemangatinya",
      correctAnswer: "c",
      orderIndex: 14,
    },
    {
      text: "Apa yang sebaiknya kita minum sebelum dan sesudah berolahraga basket?",
      optionA: "Air putih",
      optionB: "Minuman soda",
      optionC: "Kopi",
      correctAnswer: "a",
      orderIndex: 15,
    },
    {
      text: "Apa yang kita lakukan pada lawan setelah pertandingan selesai?",
      optionA: "Mengejek",
      optionB: "Bersalaman dan berterima kasih",
      optionC: "Pergi begitu saja",
      correctAnswer: "b",
      orderIndex: 16,
    },
    {
      text: "Apa manfaat bermain basket bagi tubuh kita?",
      optionA: "Membuat badan lemas",
      optionB: "Membuat badan sakit",
      optionC: "Membuat badan sehat dan kuat",
      correctAnswer: "c",
      orderIndex: 17,
    },
    {
      text: "Apa yang harus dilakukan setelah selesai bermain basket?",
      optionA: "Pendinginan dan istirahat",
      optionB: "Langsung tidur di lapangan",
      optionC: "Lari kencang lagi",
      correctAnswer: "a",
      orderIndex: 18,
    },
    {
      text: "Ketika mendribble bola, apa yang kita gunakan untuk memantulkan bola?",
      optionA: "Kepala",
      optionB: "Telapak tangan",
      optionC: "Siku",
      correctAnswer: "b",
      orderIndex: 19,
    },
    {
      text: "Apa nama gerakan melempar bola dengan dua tangan dari dada ke teman?",
      optionA: "Bounce shot",
      optionB: "Slam dunk",
      optionC: "Chest pass",
      correctAnswer: "c",
      orderIndex: 20,
    },
    {
      text: "Apa yang harus kita lakukan sebelum menembak bola ke ring?",
      optionA: "Fokus melihat ring",
      optionB: "Menutup mata",
      optionC: "Berteriak keras",
      correctAnswer: "a",
      orderIndex: 21,
    },
    {
      text: "Apa nama posisi berdiri kaki yang benar saat akan mendribble bola?",
      optionA: "Kaki lurus kaku",
      optionB: "Sedikit menekuk lutut",
      optionC: "Berjinjit",
      correctAnswer: "b",
      orderIndex: 22,
    },
    {
      text: "Kapan sebaiknya kita melakukan passing kepada teman satu tim?",
      optionA: "Saat teman dijaga ketat lawan",
      optionB: "Saat teman menjauh",
      optionC: "Saat teman berada di posisi bebas",
      correctAnswer: "c",
      orderIndex: 23,
    },
    {
      text: "Apa manfaat melakukan pemanasan sebelum bermain basket?",
      optionA: "Mencegah cedera",
      optionB: "Membuat cepat lelah",
      optionC: "Tidak ada manfaatnya",
      correctAnswer: "a",
      orderIndex: 24,
    },
    {
      text: "Apa sebutan untuk latihan menembak bola berulang-ulang agar mahir?",
      optionA: "Latihan traveling",
      optionB: "Latihan shooting",
      optionC: "Latihan foul",
      correctAnswer: "b",
      orderIndex: 25,
    },
  ] as RawQuestion[],
};
